FROM rocker/verse:4.3.3
RUN apt-get update -y && apt-get install -y  libnode-dev libcurl4-openssl-dev libssl-dev  libicu-dev  libcurl4-openssl-dev libssl-dev make zlib1g-dev  make  make pandoc libicu-dev  libcurl4-openssl-dev libssl-dev  rustc cargo make pandoc libicu-dev zlib1g-dev  make zlib1g-dev pandoc libicu-dev  make zlib1g-dev  libnode-dev libcurl4-openssl-dev libssl-dev make pandoc libxml2-dev  make pandoc  pandoc  make pandoc libpng-dev libgdal-dev gdal-bin libgeos-dev libproj-dev libsqlite3-dev  libssl-dev  libpng-dev  libgdal-dev gdal-bin libgeos-dev libproj-dev libsqlite3-dev  git  libssl-dev libgdal-dev gdal-bin libgeos-dev libproj-dev libsqlite3-dev libudunits2-dev  libudunits2-dev  zlib1g-dev  libxml2-dev && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /usr/local/lib/R/etc/ /usr/lib/R/etc/
RUN echo "options(renv.config.pak.enabled = TRUE, repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" | tee /usr/local/lib/R/etc/Rprofile.site | tee /usr/lib/R/etc/Rprofile.site
RUN R -e 'install.packages(c("renv","remotes"))'
COPY renv.lock.prod renv.lock
RUN R -e 'renv::restore()'
