globalVariables(c("Abs_diff" , "Ankuenfte", "Bettenmonat", "Country", "Destination", "Indicator", "Jahr", "Kt",
                  "Logiernaechte", "Logiernaechte_total", "Monat", "Referenz", "TotalLN", "Value",
                  "bed_occ", "beobachtung_logiernaechte", "beobachtungsjahr", "beobachtungsjahrAK",
                  "beobachtungsjahrLN", "df_prep", "dur_stay", "dur_stay_beobachtung",
                  "dur_stay_diff_abs", "dur_stay_referenz", "marktanteil", "marktanteil_diff",
                  "marktanteil_referenz", "percent_change", "percent_changeLN",
                  "referenz_logiernaechte", "referenzjahr", "referenzjahrAK", "referenzjahrLN",
                  "region_type", "Aggregat", "Betriebe", "Betten", "Zimmer", "hot_size",
                  "Betriebsgroesse", "Betriebe_total","Betten_total", "Country2", "CountryAK",
                  "CountryLN", "Total", "Zimmernaechte", "NettoBett", "NettoZimm", ".data",
                  "Ankuenfte_total", "Zimmermonat", "bed_net_occ", "room_net_occ", "room_occ"))
